// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxkjlsikleqobsbthpvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4a2psc2lrbGVxb2JzYnRocHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODc4OTEsImV4cCI6MjA2NjU2Mzg5MX0.VMS-IQ2F4pZaX94G83Tk3Q7O7wgr8zHWdC20o4534k0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);